<?php

/**
 * @file
 * Code for the Hedley General feature.
 */

// Maximal number of days that may pass between the date on which test
// execution was recorded, and the date when the results should be set.
define('HEDLEY_GENERAL_LAB_EXPIRATION_PERIOD', 35);

/**
 * Creating a new AQ task of a specific queue if not exist.
 *
 * @param string $machine_name
 *   The machine name of the queue.
 * @param int|string $unique_id
 *   An arbitrary ID to avoid duplicating tasks.
 * @param array $data
 *   The data to add to the AQ task.
 * @param array $statuses
 *   Optional; The task statuses which considered as exist.
 *
 * @return int
 *   Task ID, if created successfully.
 */
function hedley_general_add_task_to_advanced_queue_by_id($machine_name, $unique_id, array $data, array $statuses = [
  ADVANCEDQUEUE_STATUS_QUEUED,
  ADVANCEDQUEUE_STATUS_PROCESSING,
]) {
  // Make sure a task with the same ID doesn't exist already in the given
  // queue, using the queue machine name as a prefix.
  // (the `$task_title` us being used as a unique ID for the given queue).
  $task_title = $machine_name . '_' . $unique_id;
  if (hedley_general_advanced_queue_task_exists($machine_name, $task_title, $statuses)) {
    // Prevent from flooding the queue.
    return FALSE;
  }

  return hedley_general_add_task_to_advanced_queue($machine_name, ['title' => $task_title] + $data);
}

/**
 * Check whether a specific task exists, and not yet / being processed.
 *
 * @param string $queue_machine_name
 *   The machine name of the queue.
 * @param string $title
 *   The title of the task to search.
 * @param array $statuses
 *   The statuses to filter by.
 *
 * @return bool
 *   TRUE if the task exists and not and not yet / being processed.
 */
function hedley_general_advanced_queue_task_exists($queue_machine_name, $title, array $statuses = [
  ADVANCEDQUEUE_STATUS_QUEUED,
  ADVANCEDQUEUE_STATUS_PROCESSING,
]) {
  $tasks = db_select('advancedqueue', 'aq')
    ->fields('aq', ['item_id', 'status', 'created'])
    ->condition('title', $title)
    ->condition('name', $queue_machine_name)
    ->condition('status', $statuses, 'IN')
    ->range(0, 100)
    ->execute()
    ->fetchAll();

  foreach ($tasks as $task) {
    if ($task->status == ADVANCEDQUEUE_STATUS_QUEUED) {
      // Task did not start processing.
      return TRUE;
    }

    if ($task->status == ADVANCEDQUEUE_STATUS_PROCESSING) {
      if (time() - $task->created < variable_get('hedley_aq_task_max_processing_period', 20 * 60)) {
        // Task is being processed, and did not exceed allowed time period,
        // which is set to 20 minutes, by default.
        return TRUE;
      }
    }
  }

  return FALSE;
}

/**
 * Add a new task to a specific advanced queue.
 *
 * @param string $queue_machine_name
 *   The machine name of the queue.
 * @param array $task_arguments
 *   The arguments we should pass to the task.
 *
 * @return int
 *   The new advancedqueue_item ID.
 */
function hedley_general_add_task_to_advanced_queue($queue_machine_name, array $task_arguments) {
  // Get the requested queue.
  $queue = new AdvancedQueue($queue_machine_name);

  $task = [
    'timestamp' => REQUEST_TIME,
  ];

  $task += $task_arguments;

  $item_id = $queue->createItem($task);

  if (!$item_id) {
    $args = [
      '@name' => $queue_machine_name,
      '@args' => serialize($task),
    ];
    drupal_set_message(format_string('Failed to create AQ job for queue "@name". Item arguments: "@args"', $args), 'error');
  }

  return $item_id;
}

/**
 * Get the AQ Item ID by name.
 *
 * @param string $item_title
 *   The unique AQ Item name.
 * @param bool $all_status
 *   Determine if AQ of any status should be retrieved. Defaults to FALSE.
 *
 * @return bool|int
 *   FALSE if no Advanced queue Item is found, otherwise its ID.
 */
function hedley_general_get_aq_item_by_title($item_title, $all_status = FALSE) {
  $status = [
    ADVANCEDQUEUE_STATUS_QUEUED,
    ADVANCEDQUEUE_STATUS_FAILURE_RETRY,
  ];

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'advancedqueue_item')
    ->propertyCondition('title', $item_title);

  if (!$all_status) {
    $query->propertyCondition('status', $status, 'IN');
  }

  $result = $query
    // Get the latest one.
    ->propertyOrderBy('item_id', 'DESC')
    ->range(0, 1)
    ->execute();

  return !empty($result['advancedqueue_item']) ? key($result['advancedqueue_item']) : FALSE;
}

/**
 * Returns a list of measurements IDs that were taken for certain person.
 *
 * @param int $person_id
 *   The ID of person we query for measurements.
 * @param array $measurement_types
 *   Optional; List of content types that are considered as measurements.
 *
 * @return array
 *   List of measurements IDs.
 */
function hedley_general_get_person_measurements($person_id, array $measurement_types = []) {
  if (empty($measurement_types)) {
    $measurement_types = hedley_general_get_measurement_types();
  }

  $query = db_select('field_data_field_person', 't');
  $query->addField('t', 'entity_id');
  $query->condition('bundle', $measurement_types, 'IN');
  $query->condition('field_person_target_id', $person_id);

  return $query->execute()->fetchCol();
}

/**
 * Resolves all content associated with person using association fields.
 *
 * For example, 'field_person' associates all measurements taken for person.
 *
 * @param int $person_id
 *   Node ID of the person.
 * @param array $fields
 *   List of association fields.
 *
 * @return array
 *   List of pairs (node ID + bundle) of content associated with person.
 */
function hedley_general_get_person_content_associated_by_fields($person_id, array $fields) {
  $content = [];

  foreach ($fields as $field) {
    $query = db_select("field_data_$field", 't');
    $query->addField('t', 'entity_id');
    $query->addField('t', 'bundle');
    $query->condition("${field}_target_id", $person_id);

    $content = array_merge($content, $query->execute()->fetchAll());
  }

  return $content;
}

/**
 * Returns list of content types that are considered as measurements.
 *
 * We return both group and individual encounters measurements.
 *
 * @return array
 *   List of content types that are considered as measurements.
 */
function hedley_general_get_measurement_types() {
  $measurement_types = [];
  $content_types = array_keys(node_type_get_types());
  $encounter_types = hedley_general_get_encounter_types();
  $measurement_indicator_fields = [];
  foreach ($encounter_types as $encounter_type) {
    $measurement_indicator_fields[] = "field_$encounter_type";
  }

  foreach ($content_types as $content_type) {
    $fields = hedley_general_get_content_type_fields($content_type);

    foreach ($measurement_indicator_fields as $indicator) {
      if (in_array($indicator, $fields)) {
        $measurement_types[] = $content_type;
        break;
      }
    }
  }

  return $measurement_types;
}

/**
 * Returns list of content types that are considered as encounters.
 *
 * Both group and individual encounters are returned.
 *
 * @return array
 *   List of content types that are considered as encounters.
 */
function hedley_general_get_encounter_types() {
  $types = hedley_general_get_individual_encounter_types();
  // Session represents group encounter.
  $types[] = 'session';

  return $types;
}

/**
 * Returns a list of individual encounters content type names.
 *
 * @return array
 *   List of individual encounters content type names.
 */
function hedley_general_get_individual_encounter_types() {
  $encounter_types = [];
  $content_types = array_keys(node_type_get_types());

  // As a convention, name of encounter content type ends with `_encounter`.
  foreach ($content_types as $type) {
    if (preg_match('/_encounter$/', $type)) {
      $encounter_types[] = $type;
    }
  }

  return $encounter_types;
}

/**
 * Returns list of fields names on certain content type.
 *
 * @param string $type
 *   Content type bundle.
 *
 * @return array
 *   List of fields names.
 */
function hedley_general_get_content_type_fields($type) {
  $query = db_select('field_config_instance', 'ci');
  $query->addField('ci', 'field_name');
  $query->condition('bundle', $type);

  return $query->execute()->fetchCol();
}

/**
 * Creates an EntityFieldQuery with the exclude_deleted tag pre-applied.
 */
function hedley_general_create_entity_field_query_excluding_deleted() {
  $query = new EntityFieldQuery();
  $query->addTag('exclude_deleted');
  return $query;
}

/**
 * Implements hook_query_TAG_alter().
 *
 * Adds a condition to select entities that have field_deleted set
 * to False, or not set at all (an indication that entity is not deleted).
 */
function hedley_general_query_exclude_deleted_alter(QueryAlterableInterface $query) {
  $query->leftJoin('field_data_field_deleted', 'fd', 'node.nid = fd.entity_id');
  $or = db_or()
    ->isNull('fd.field_deleted_value')
    ->condition('fd.field_deleted_value', FALSE);
  $query->condition($or);
}

/**
 * Join a field to a DB Select query, and add its main value.
 *
 * @param SelectQuery $query
 *   Query to join to.
 * @param string $entity_type
 *   Type of the host entity of the field. Or NULL to avoid filtering the field
 *   table by entity type.
 * @param string $field_name
 *   Field name.
 * @param bool $require
 *   Whether filter out rows where this field would be NULL.
 * @param string $entity_id_selector
 *   SQL selector for the column by which the field is joined. The entity ID is
 *   used by default.
 * @param string $field_alias
 *   The field alias.
 *
 * @throws Exception
 */
function hedley_general_join_field_to_query(SelectQuery $query, $entity_type, $field_name, $require = TRUE, $entity_id_selector = NULL, $field_alias = NULL, $second_value = FALSE) {
  $field = field_info_field($field_name);
  $table_name = _field_sql_storage_tablename($field);

  if (!$entity_id_selector) {
    if (!$entity_type) {
      throw new Exception('Entity type is required when ID selector is not specified');
    }
    // Set default entity ID selector.
    switch ($entity_type) {
      case 'user':
        $entity_id_selector = 'users.uid';
        break;

      case 'node':
        $entity_id_selector = 'node.nid';
        break;

      default:
        throw new Exception(format_string('hedley_general_join_field_to_query() is not implemented for entity_type: "@type"', ['@type' => $entity_type]));
    }
  }

  switch ($field['type']) {
    case 'entityreference':
      $column_suffix = 'target_id';
      break;

    case 'image':
    case 'file':
      $column_suffix = 'fid';
      break;

    default:
      $column_suffix = 'value';
  }

  $field_alias = $field_alias ?: $field_name;
  $query->addField($field_alias, $field_name . '_' . $column_suffix, $field_alias);
  if ($second_value) {
    $column_suffix = 'value2';
    $query->addField($field_alias, $field_name . '_' . $column_suffix, $field_alias);
  }

  $join = $require ? 'innerJoin' : 'leftJoin';
  $arguments = [':type' => $entity_type];
  $conditions[] = "$entity_id_selector = $field_alias.entity_id";
  if ($entity_type) {
    $conditions[] = "$field_alias.entity_type = :type";
  }

  $query->$join($table_name, $field_alias, implode(' AND ', $conditions), $arguments);
}

/**
 * Resolve a shard based on HC field of the node.
 *
 * @param int $nid
 *   The node ID.
 *
 * @return int|bool
 *   Node ID of the shard. False, if shard wasn't successfully resolved.
 */
function hedley_general_shard_by_health_center($nid) {
  // We have this check to allow SimpleTest to pass.
  if (!$nid) {
    return FALSE;
  }

  $wrapper = entity_metadata_wrapper('node', $nid);
  if (!isset($wrapper->field_health_center)) {
    return FALSE;
  }
  $shard = $wrapper->field_health_center->getIdentifier();

  return !empty($shard) ? $shard : FALSE;
}

/**
 * Resolve shards based on Person field of the node.
 *
 * @param int $nid
 *   The node ID.
 *
 * @return array
 *   List of shards node IDs. Empty array, if none are found.
 */
function hedley_general_shards_by_person($nid) {
  // We have this check to allow SimpleTest to pass.
  if (!$nid) {
    return [];
  }

  $wrapper = entity_metadata_wrapper('node', $nid);
  if (!isset($wrapper->field_shards)) {
    return [];
  }
  $shards = $wrapper->field_shards->value(['identifier' => TRUE]);

  return !empty($shards) ? $shards : [];
}

/**
 * Implements hook_file_presave().
 *
 * If file is saved directly into 'private', sets it's uri and
 * destination to storage sub folder (storage-MM-YYYY).
 * Exception are whatsapp screenshots that should remain at public, since
 * they get deleted after few hours anyway.
 * We need this, so that photos that are fetched from client get correct
 * uri for image style into 'deferredPhotos' table, which is used to
 * download deferred photos during device sync.
 * The file itself will be moved to storage folder at hook_file_insert().
 */
function hedley_general_file_presave($file) {
  $valid = FALSE;
  $valid_prefixes = [
    'image-',
    'signature-',
  ];
  foreach ($valid_prefixes as $prefix) {
    if (strpos($file->filename, $prefix) === 0) {
      $valid = TRUE;
      break;
    }
  }

  if (!$valid || $file->uri !== 'private://' . $file->filename) {
    return;
  }

  // Generate storages sub-folder name per current date.
  $target_folder = 'private://storage-' . date('m-Y', time()) . '/';
  if (!file_prepare_directory($target_folder, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
    return;
  }

  $new_uri = str_replace('private://', $target_folder, $file->uri);
  $file->uri = $new_uri;
  $file->destination = $new_uri;
}

/**
 * Implements hook_file_insert().
 *
 * At hook_file_presave(), file uri is set to storage sub-folder.
 * If such file is inserted, we move the file from 'private' to
 * storage sub-folder.
 */
function hedley_general_file_insert($file) {
  $file = file_load($file->fid);
  if (strstr($file->uri, 'private://storage-') === FALSE) {
    return;
  }

  $destination = $file->uri;
  $file->uri = 'private://' . $file->filename;
  file_move($file, $destination);
}

/**
 * Build Elm application for aggregated NCDA.
 *
 * @param string $page
 *   The page name.
 * @param array $data
 *   The data array to be used by Elm application.
 *
 * @return string
 *   The HTML markup for the Elm application.
 */
function hedley_general_build_elm_app($page, array $data) {
  $path_hedley_general = drupal_get_path('module', 'hedley_general');

  // Add scripts.
  drupal_add_js($path_hedley_general . '/js/elm-main.js');
  drupal_add_js($path_hedley_general . '/js/elm.js');

  // Add CSS for all pages.
  drupal_add_css($path_hedley_general . '/css/elm.css', 'file');
  drupal_add_css($path_hedley_general . '/css/date-selector.css', 'file');

  if (in_array($page, ['ncda-results', 'reports-results', 'completion-results'])) {
    // Add CSS for results pages.
    $path_system = drupal_get_path('module', 'system');
    drupal_add_css($path_system . '/system.base.css', 'file');
    drupal_add_css($path_system . '/system.menus.css', 'file');
    $default_theme = variable_get('theme_default', 'bartik');
    $path_theme = drupal_get_path('theme', $default_theme);
    drupal_add_css($path_theme . '/css/style.css', 'file');
    drupal_add_css($path_theme . '/css/layout.css', 'file');
    drupal_add_css($path_theme . '/css/colors.css', 'file');
  }

  // Getting a unique ID for the app.
  $app_id = drupal_html_id('elm-app');

  // Add settings.
  $settings = [
    'elm_apps' => [
      $app_id => [
        'page' => $page,
        'data' => $data,
        'theme_path' => $path_hedley_general,
      ],
    ],
  ];
  drupal_add_js($settings, 'setting');

  // Return the HTML markup for the Elm application.
  return '<div id="' . $app_id . '"></div>';
}
