<?php

/**
 * @file
 * Code for the Hedley CHW feature.
 */

include_once 'hedley_chw.features.inc';

/**
 * Implements hook_node_insert().
 *
 * Crate CHW group for newly created village.
 */
function hedley_chw_node_insert($node) {
  if ($node->type != 'village') {
    return;
  }

  // Create CHW group for new village.
  $wrapper = entity_metadata_wrapper('node', $node);
  $village_name = $wrapper->label();
  $health_center_id = $wrapper->field_health_center->getIdentifier();

  $clinic_node = entity_create('node', [
    'type' => 'clinic',
    'uid' => $node->uid,
  ]);

  $clinic_wrapper = entity_metadata_wrapper('node', $clinic_node);
  $clinic_wrapper->title->set("$village_name CHW group");
  $clinic_wrapper->field_health_center->set($health_center_id);
  $clinic_wrapper->field_village_ref->set($node->nid);
  $clinic_wrapper->field_group_type->set('chw');
  $clinic_wrapper->save();

  $clinic = $clinic_wrapper->getIdentifier();

  $residents = hedley_chw_get_village_residents($node->id);
  if (empty($residents)) {
    return;
  }

  // Create participants for the clinic.
  $batch_size = 50;
  $offset = 0;

  // A query that loads relationship for village. Since we create relations
  // only for adults, we won't get duplicates here.
  $relationships_query = new EntityFieldQuery();
  $relationships_query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'relationship')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_person', 'target_id', $residents)
    ->propertyOrderBy('nid', 'ASC');

  $relationships_query_count = clone $relationships_query;
  $count = $relationships_query_count->count()->execute();

  // Execute creation in a batch.
  while ($offset < $count) {
    $query = clone $relationships_query;

    $result = $query
      ->range($offset, $batch_size)
      ->execute();

    if (empty($result['node'])) {
      return;
    }

    $keys = array_keys($result['node']);
    $relationships = node_load_multiple($keys);

    foreach ($relationships as $relationship) {
      $relationships_wrapper = entity_metadata_wrapper('node', $relationship);

      // Skip relationships where child age is over 5 years.
      $child_birth_date = $relationships_wrapper->field_related_to->field_birth_date->value();
      if ($child_birth_date < strtotime("-5 year")) {
        continue;
      }

      $adult = $relationships_wrapper->field_person->getIdentifier();
      $child = $relationships_wrapper->field_related_to->getIdentifier();
      $related_by = $relationships_wrapper->field_related_by->value();
      $adult_activities = $related_by == HEDLEY_PERSON_RELATED_BY_CAREGIVER_FOR ?
        HEDLEY_SCHEDULE_PMTCT_ACTIVITIES_CAREGIVER : HEDLEY_SCHEDULE_PMTCT_ACTIVITIES_MOTHER;

      $participant_node = entity_create('node', [
        'type' => 'pmtct_participant',
        'uid' => $node->uid,
      ]);
      $participant_wrapper = entity_metadata_wrapper('node', $participant_node);
      $participant_wrapper->field_adult->set($adult);
      $participant_wrapper->field_person->set($child);
      $participant_wrapper->field_adult_activities->set($adult_activities);
      $participant_wrapper->field_expected->set([
        'value' => date('Y-m-d'),
        'value2' => NULL,
      ]);
      $participant_wrapper->field_clinic->set($clinic);
      $participant_wrapper->save();
    }

    $offset += $batch_size;

    // Free up memory.
    drupal_static_reset();
  }
}

/**
 * Retrieves the IDs of all people that live in given village.
 *
 * @param int $nid
 *   Village node ID.
 * @param int $range
 *   The queries' range.
 *
 * @return array
 *   List of IDs of all people that live in given village.
 *
 * @throws \EntityMetadataWrapperException
 */
function hedley_chw_get_village_residents($nid, $range = 1000) {
  $wrapper = entity_metadata_wrapper('node', $nid);
  $province = $wrapper->field_province->value();
  $district = $wrapper->field_district->value();
  $sector = $wrapper->field_sector->value();
  $cell = $wrapper->field_cell->value();
  $village = $wrapper->field_village->value();

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'person')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_province', 'value', $province)
    ->fieldCondition('field_district', 'value', $district)
    ->fieldCondition('field_sector', 'value', $sector)
    ->fieldCondition('field_cell', 'value', $cell)
    ->fieldCondition('field_village', 'value', $village)
    ->addTag('exclude_deleted')
    ->range(0, $range)
    ->execute();

  return empty($result['node']) ? [] : array_keys($result['node']);
}
