sudo: required
language: php
php:
- 7.2
env:
  matrix:
  - BUILD_SERVER=1
  # - BUILD_CLIENT=1
  - CODE_REVIEW=1 REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1 REVIEW_STANDARD="DrupalPractice"
  - SHELL_REVIEW=1
  - ELM_REVIEW=1
services:
- docker
before_install:
- export PATH="$HOME/.config/composer/vendor/bin:$PATH"
- "([ ! -z $BUILD_WEBDRIVERIO ] && sudo pip install docker-compose) || :"
install:
- "$TRAVIS_BUILD_DIR/ci-scripts/install_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_shell.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/install_elm_format.sh"
before_script:
- "$TRAVIS_BUILD_DIR/ci-scripts/prepare_client.sh"
script:
- "$TRAVIS_BUILD_DIR/ci-scripts/test_client.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_server.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_shell.sh"
- "$TRAVIS_BUILD_DIR/ci-scripts/test_elm_format.sh"
cache:
  directories:
  - client/elm-stuff/packages
  - client/sysconfcpus
  - travis-cache
