<?php

/**
 * @file
 * hedley_hiv.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function hedley_hiv_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function hedley_hiv_node_info() {
  $items = array(
    'hiv_diagnostics' => array(
      'name' => t('HIV Diagnostics'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'hiv_encounter' => array(
      'name' => t('HIV Encounter'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'hiv_follow_up' => array(
      'name' => t('HIV Follow Up'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'hiv_health_education' => array(
      'name' => t('HIV Health Education'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'hiv_medication' => array(
      'name' => t('HIV Medication'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'hiv_referral' => array(
      'name' => t('HIV Referral'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'hiv_symptom_review' => array(
      'name' => t('HIV Symptom Review'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'hiv_treatment_review' => array(
      'name' => t('HIV Treatment Review'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
