<?php

/**
 * @file
 * Code for the Hedley WhatsApp feature.
 */

include_once 'hedley_whatsapp.features.inc';

define('HEDLEY_WHATSAPP_ENGLISH_CODE', 'en');

/**
 * Returns the progress report message template based on language.
 * If no template is set for the language, defaults to English template.
 *
 * @param string $language
 *   The language code for the template.
 *
 * @return string
 *   The progress report message template.
 */
function hedley_whatsapp_get_progress_report_messasge_template($language) {
  $default = "Hi from Tip Global Health!\n\nThe @report-type progress report for @patient-name from @date.\n\n Thank you.";
  $english_template_variable = 'hedley_whatsapp_message_template_' . HEDLEY_WHATSAPP_ENGLISH_CODE;
  $english_template = variable_get($english_template_variable, $default);
  if ($language == HEDLEY_WHATSAPP_ENGLISH_CODE) {
    return $english_template;
  }

  $template_variable = "hedley_whatsapp_message_template_$language";
  return variable_get($template_variable, $english_template);
}