<?php

/**
 * @file
 * hedley_nutrition.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function hedley_nutrition_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_child_caring_options'.
  $field_bases['field_child_caring_options'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_child_caring_options',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'parent' => 'Parent',
        'grandparent' => ' Grandparent',
        'sibling' => ' Sibling',
        'neighbor' => ' Neighbor',
        'daycare' => ' DayCare',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_contributing_factors_signs'.
  $field_bases['field_contributing_factors_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_contributing_factors_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'lack-of-breast-milk' => 'Lack of breast milk',
        'maternal-mastitis' => 'Maternal mastitis',
        'poor-suck' => 'Poor suck',
        'diarrhea-or-vomiting' => 'Diarrhea or vomiting',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_follow_up_options'.
  $field_bases['field_follow_up_options'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_follow_up_options',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        '1-d' => '1 Day',
        '3-d' => '3 Days',
        '1-w' => '1 Week',
        '2-w' => '2 Weeks',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_food_security_signs'.
  $field_bases['field_food_security_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_food_security_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'household-got-food' => 'Household Got Food',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_home_visit_encounter'.
  $field_bases['field_home_visit_encounter'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_home_visit_encounter',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'home_visit_encounter' => 'home_visit_encounter',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_main_income_source'.
  $field_bases['field_main_income_source'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_main_income_source',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'home-based-agriculture' => 'Home Based Agriculture',
        'commercial-agriculture' => 'Commercial Agriculture',
        'public-employee' => 'Public Employee',
        'private-business-employee' => 'Private Business Employee',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_main_water_source'.
  $field_bases['field_main_water_source'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_main_water_source',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'piped-water-to-home' => 'Piped Water to Home',
        'public-water-tap' => 'Public Water Tap',
        'rain-water-collection-system' => 'Rain Water Collection System',
        'natural-source-flowing-water' => 'Natural Source Flowing Water',
        'natural-source-standing-water' => 'Natural Source Standing Water',
        'bottled-water' => 'Bottled Water',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_nutrition_caring_questions'.
  $field_bases['field_nutrition_caring_questions'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_nutrition_caring_questions',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'parent-alive-and-healthy' => 'Parents alive and healthy',
        'child-clean' => 'Child clean',
        'none' => 'None of these',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_nutrition_feeding_signs'.
  $field_bases['field_nutrition_feeding_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_nutrition_feeding_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'receive-supplement' => 'Receive supplement',
        'ration-present-at-home' => 'Ration present at home',
        'enough-till-next-session' => 'Enough till next session',
        'supplement-shared' => 'Supplement shared',
        'encouraged-to-eat' => 'Encouraged to eat',
        'refusing-to-eat' => 'Refusing to eat',
        'breastfeeding' => 'Breastfeeding',
        'clean-water-available' => 'Clean water available',
        'eaten-with-water' => 'Eaten with water',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_nutrition_hygiene_signs'.
  $field_bases['field_nutrition_hygiene_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_nutrition_hygiene_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'soap-in-the-house' => 'Soap in the House',
        'wash-hands-before-feeding' => 'Wash Hands Before Feeding',
        'food-covered' => 'Food Covered',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_sachets_per_day'.
  $field_bases['field_sachets_per_day'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_sachets_per_day',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_supplement_type'.
  $field_bases['field_supplement_type'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_supplement_type',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'fortified-porridge' => 'Fortified porridge',
        'rutf' => 'RUTF',
        'ongera' => 'Ongera',
        'therapeutic-milk' => 'Therapeutik milk',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
