
# You can copy this Dockerfile.example to Dockerfile to add configuration
# or packages or anything else to your dbimage
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN echo "Built from drud/ddev-dbserver-mariadb-10.2:v1.14.1" >/var/tmp/built-from.txt
