<?php

/**
 * @file
 * hedley_ncd.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function hedley_ncd_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'create ncd_co_morbidities content'.
  $permissions['create ncd_co_morbidities content'] = array(
    'name' => 'create ncd_co_morbidities content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_core_exam content'.
  $permissions['create ncd_core_exam content'] = array(
    'name' => 'create ncd_core_exam content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_creatinine_test content'.
  $permissions['create ncd_creatinine_test content'] = array(
    'name' => 'create ncd_creatinine_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_danger_signs content'.
  $permissions['create ncd_danger_signs content'] = array(
    'name' => 'create ncd_danger_signs content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_family_history content'.
  $permissions['create ncd_family_history content'] = array(
    'name' => 'create ncd_family_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_family_planning content'.
  $permissions['create ncd_family_planning content'] = array(
    'name' => 'create ncd_family_planning content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_hba1c_test content'.
  $permissions['create ncd_hba1c_test content'] = array(
    'name' => 'create ncd_hba1c_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_health_education content'.
  $permissions['create ncd_health_education content'] = array(
    'name' => 'create ncd_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_hiv_test content'.
  $permissions['create ncd_hiv_test content'] = array(
    'name' => 'create ncd_hiv_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_labs_results content'.
  $permissions['create ncd_labs_results content'] = array(
    'name' => 'create ncd_labs_results content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_lipid_panel_test content'.
  $permissions['create ncd_lipid_panel_test content'] = array(
    'name' => 'create ncd_lipid_panel_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_liver_function_test content'.
  $permissions['create ncd_liver_function_test content'] = array(
    'name' => 'create ncd_liver_function_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_medication_distribution content'.
  $permissions['create ncd_medication_distribution content'] = array(
    'name' => 'create ncd_medication_distribution content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_medication_history content'.
  $permissions['create ncd_medication_history content'] = array(
    'name' => 'create ncd_medication_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_outside_care content'.
  $permissions['create ncd_outside_care content'] = array(
    'name' => 'create ncd_outside_care content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_pregnancy_test content'.
  $permissions['create ncd_pregnancy_test content'] = array(
    'name' => 'create ncd_pregnancy_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_random_blood_sugar_test content'.
  $permissions['create ncd_random_blood_sugar_test content'] = array(
    'name' => 'create ncd_random_blood_sugar_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_referral content'.
  $permissions['create ncd_referral content'] = array(
    'name' => 'create ncd_referral content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_social_history content'.
  $permissions['create ncd_social_history content'] = array(
    'name' => 'create ncd_social_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_symptom_review content'.
  $permissions['create ncd_symptom_review content'] = array(
    'name' => 'create ncd_symptom_review content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_urine_dipstick_test content'.
  $permissions['create ncd_urine_dipstick_test content'] = array(
    'name' => 'create ncd_urine_dipstick_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create ncd_vitals content'.
  $permissions['create ncd_vitals content'] = array(
    'name' => 'create ncd_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_co_morbidities content'.
  $permissions['delete any ncd_co_morbidities content'] = array(
    'name' => 'delete any ncd_co_morbidities content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_core_exam content'.
  $permissions['delete any ncd_core_exam content'] = array(
    'name' => 'delete any ncd_core_exam content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_creatinine_test content'.
  $permissions['delete any ncd_creatinine_test content'] = array(
    'name' => 'delete any ncd_creatinine_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_danger_signs content'.
  $permissions['delete any ncd_danger_signs content'] = array(
    'name' => 'delete any ncd_danger_signs content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_family_history content'.
  $permissions['delete any ncd_family_history content'] = array(
    'name' => 'delete any ncd_family_history content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_family_planning content'.
  $permissions['delete any ncd_family_planning content'] = array(
    'name' => 'delete any ncd_family_planning content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_hba1c_test content'.
  $permissions['delete any ncd_hba1c_test content'] = array(
    'name' => 'delete any ncd_hba1c_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_health_education content'.
  $permissions['delete any ncd_health_education content'] = array(
    'name' => 'delete any ncd_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_hiv_test content'.
  $permissions['delete any ncd_hiv_test content'] = array(
    'name' => 'delete any ncd_hiv_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_labs_results content'.
  $permissions['delete any ncd_labs_results content'] = array(
    'name' => 'delete any ncd_labs_results content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_lipid_panel_test content'.
  $permissions['delete any ncd_lipid_panel_test content'] = array(
    'name' => 'delete any ncd_lipid_panel_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_liver_function_test content'.
  $permissions['delete any ncd_liver_function_test content'] = array(
    'name' => 'delete any ncd_liver_function_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_medication_distribution content'.
  $permissions['delete any ncd_medication_distribution content'] = array(
    'name' => 'delete any ncd_medication_distribution content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_medication_history content'.
  $permissions['delete any ncd_medication_history content'] = array(
    'name' => 'delete any ncd_medication_history content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_outside_care content'.
  $permissions['delete any ncd_outside_care content'] = array(
    'name' => 'delete any ncd_outside_care content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_pregnancy_test content'.
  $permissions['delete any ncd_pregnancy_test content'] = array(
    'name' => 'delete any ncd_pregnancy_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_random_blood_sugar_test content'.
  $permissions['delete any ncd_random_blood_sugar_test content'] = array(
    'name' => 'delete any ncd_random_blood_sugar_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_referral content'.
  $permissions['delete any ncd_referral content'] = array(
    'name' => 'delete any ncd_referral content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_social_history content'.
  $permissions['delete any ncd_social_history content'] = array(
    'name' => 'delete any ncd_social_history content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_symptom_review content'.
  $permissions['delete any ncd_symptom_review content'] = array(
    'name' => 'delete any ncd_symptom_review content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_urine_dipstick_test content'.
  $permissions['delete any ncd_urine_dipstick_test content'] = array(
    'name' => 'delete any ncd_urine_dipstick_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any ncd_vitals content'.
  $permissions['delete any ncd_vitals content'] = array(
    'name' => 'delete any ncd_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_co_morbidities content'.
  $permissions['delete own ncd_co_morbidities content'] = array(
    'name' => 'delete own ncd_co_morbidities content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_core_exam content'.
  $permissions['delete own ncd_core_exam content'] = array(
    'name' => 'delete own ncd_core_exam content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_creatinine_test content'.
  $permissions['delete own ncd_creatinine_test content'] = array(
    'name' => 'delete own ncd_creatinine_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_danger_signs content'.
  $permissions['delete own ncd_danger_signs content'] = array(
    'name' => 'delete own ncd_danger_signs content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_family_history content'.
  $permissions['delete own ncd_family_history content'] = array(
    'name' => 'delete own ncd_family_history content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_family_planning content'.
  $permissions['delete own ncd_family_planning content'] = array(
    'name' => 'delete own ncd_family_planning content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_hba1c_test content'.
  $permissions['delete own ncd_hba1c_test content'] = array(
    'name' => 'delete own ncd_hba1c_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_health_education content'.
  $permissions['delete own ncd_health_education content'] = array(
    'name' => 'delete own ncd_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_hiv_test content'.
  $permissions['delete own ncd_hiv_test content'] = array(
    'name' => 'delete own ncd_hiv_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_labs_results content'.
  $permissions['delete own ncd_labs_results content'] = array(
    'name' => 'delete own ncd_labs_results content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_lipid_panel_test content'.
  $permissions['delete own ncd_lipid_panel_test content'] = array(
    'name' => 'delete own ncd_lipid_panel_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_liver_function_test content'.
  $permissions['delete own ncd_liver_function_test content'] = array(
    'name' => 'delete own ncd_liver_function_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_medication_distribution content'.
  $permissions['delete own ncd_medication_distribution content'] = array(
    'name' => 'delete own ncd_medication_distribution content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_medication_history content'.
  $permissions['delete own ncd_medication_history content'] = array(
    'name' => 'delete own ncd_medication_history content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_outside_care content'.
  $permissions['delete own ncd_outside_care content'] = array(
    'name' => 'delete own ncd_outside_care content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_pregnancy_test content'.
  $permissions['delete own ncd_pregnancy_test content'] = array(
    'name' => 'delete own ncd_pregnancy_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_random_blood_sugar_test content'.
  $permissions['delete own ncd_random_blood_sugar_test content'] = array(
    'name' => 'delete own ncd_random_blood_sugar_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_referral content'.
  $permissions['delete own ncd_referral content'] = array(
    'name' => 'delete own ncd_referral content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_social_history content'.
  $permissions['delete own ncd_social_history content'] = array(
    'name' => 'delete own ncd_social_history content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_symptom_review content'.
  $permissions['delete own ncd_symptom_review content'] = array(
    'name' => 'delete own ncd_symptom_review content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_urine_dipstick_test content'.
  $permissions['delete own ncd_urine_dipstick_test content'] = array(
    'name' => 'delete own ncd_urine_dipstick_test content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own ncd_vitals content'.
  $permissions['delete own ncd_vitals content'] = array(
    'name' => 'delete own ncd_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_co_morbidities content'.
  $permissions['edit any ncd_co_morbidities content'] = array(
    'name' => 'edit any ncd_co_morbidities content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_core_exam content'.
  $permissions['edit any ncd_core_exam content'] = array(
    'name' => 'edit any ncd_core_exam content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_creatinine_test content'.
  $permissions['edit any ncd_creatinine_test content'] = array(
    'name' => 'edit any ncd_creatinine_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_danger_signs content'.
  $permissions['edit any ncd_danger_signs content'] = array(
    'name' => 'edit any ncd_danger_signs content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_family_history content'.
  $permissions['edit any ncd_family_history content'] = array(
    'name' => 'edit any ncd_family_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_family_planning content'.
  $permissions['edit any ncd_family_planning content'] = array(
    'name' => 'edit any ncd_family_planning content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_hba1c_test content'.
  $permissions['edit any ncd_hba1c_test content'] = array(
    'name' => 'edit any ncd_hba1c_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_health_education content'.
  $permissions['edit any ncd_health_education content'] = array(
    'name' => 'edit any ncd_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_hiv_test content'.
  $permissions['edit any ncd_hiv_test content'] = array(
    'name' => 'edit any ncd_hiv_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_labs_results content'.
  $permissions['edit any ncd_labs_results content'] = array(
    'name' => 'edit any ncd_labs_results content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_lipid_panel_test content'.
  $permissions['edit any ncd_lipid_panel_test content'] = array(
    'name' => 'edit any ncd_lipid_panel_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_liver_function_test content'.
  $permissions['edit any ncd_liver_function_test content'] = array(
    'name' => 'edit any ncd_liver_function_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_medication_distribution content'.
  $permissions['edit any ncd_medication_distribution content'] = array(
    'name' => 'edit any ncd_medication_distribution content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_medication_history content'.
  $permissions['edit any ncd_medication_history content'] = array(
    'name' => 'edit any ncd_medication_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_outside_care content'.
  $permissions['edit any ncd_outside_care content'] = array(
    'name' => 'edit any ncd_outside_care content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_pregnancy_test content'.
  $permissions['edit any ncd_pregnancy_test content'] = array(
    'name' => 'edit any ncd_pregnancy_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_random_blood_sugar_test content'.
  $permissions['edit any ncd_random_blood_sugar_test content'] = array(
    'name' => 'edit any ncd_random_blood_sugar_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_referral content'.
  $permissions['edit any ncd_referral content'] = array(
    'name' => 'edit any ncd_referral content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_social_history content'.
  $permissions['edit any ncd_social_history content'] = array(
    'name' => 'edit any ncd_social_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_symptom_review content'.
  $permissions['edit any ncd_symptom_review content'] = array(
    'name' => 'edit any ncd_symptom_review content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_urine_dipstick_test content'.
  $permissions['edit any ncd_urine_dipstick_test content'] = array(
    'name' => 'edit any ncd_urine_dipstick_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any ncd_vitals content'.
  $permissions['edit any ncd_vitals content'] = array(
    'name' => 'edit any ncd_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_co_morbidities content'.
  $permissions['edit own ncd_co_morbidities content'] = array(
    'name' => 'edit own ncd_co_morbidities content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_core_exam content'.
  $permissions['edit own ncd_core_exam content'] = array(
    'name' => 'edit own ncd_core_exam content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_creatinine_test content'.
  $permissions['edit own ncd_creatinine_test content'] = array(
    'name' => 'edit own ncd_creatinine_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_danger_signs content'.
  $permissions['edit own ncd_danger_signs content'] = array(
    'name' => 'edit own ncd_danger_signs content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_family_history content'.
  $permissions['edit own ncd_family_history content'] = array(
    'name' => 'edit own ncd_family_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_family_planning content'.
  $permissions['edit own ncd_family_planning content'] = array(
    'name' => 'edit own ncd_family_planning content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_hba1c_test content'.
  $permissions['edit own ncd_hba1c_test content'] = array(
    'name' => 'edit own ncd_hba1c_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_health_education content'.
  $permissions['edit own ncd_health_education content'] = array(
    'name' => 'edit own ncd_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_hiv_test content'.
  $permissions['edit own ncd_hiv_test content'] = array(
    'name' => 'edit own ncd_hiv_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_labs_results content'.
  $permissions['edit own ncd_labs_results content'] = array(
    'name' => 'edit own ncd_labs_results content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_lipid_panel_test content'.
  $permissions['edit own ncd_lipid_panel_test content'] = array(
    'name' => 'edit own ncd_lipid_panel_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_liver_function_test content'.
  $permissions['edit own ncd_liver_function_test content'] = array(
    'name' => 'edit own ncd_liver_function_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_medication_distribution content'.
  $permissions['edit own ncd_medication_distribution content'] = array(
    'name' => 'edit own ncd_medication_distribution content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_medication_history content'.
  $permissions['edit own ncd_medication_history content'] = array(
    'name' => 'edit own ncd_medication_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_outside_care content'.
  $permissions['edit own ncd_outside_care content'] = array(
    'name' => 'edit own ncd_outside_care content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_pregnancy_test content'.
  $permissions['edit own ncd_pregnancy_test content'] = array(
    'name' => 'edit own ncd_pregnancy_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_random_blood_sugar_test content'.
  $permissions['edit own ncd_random_blood_sugar_test content'] = array(
    'name' => 'edit own ncd_random_blood_sugar_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_referral content'.
  $permissions['edit own ncd_referral content'] = array(
    'name' => 'edit own ncd_referral content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_social_history content'.
  $permissions['edit own ncd_social_history content'] = array(
    'name' => 'edit own ncd_social_history content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_symptom_review content'.
  $permissions['edit own ncd_symptom_review content'] = array(
    'name' => 'edit own ncd_symptom_review content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_urine_dipstick_test content'.
  $permissions['edit own ncd_urine_dipstick_test content'] = array(
    'name' => 'edit own ncd_urine_dipstick_test content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own ncd_vitals content'.
  $permissions['edit own ncd_vitals content'] = array(
    'name' => 'edit own ncd_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  return $permissions;
}
