<?php

/**
 * @file
 * hedley_ncd.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function hedley_ncd_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_alt_result'.
  $field_bases['field_alt_result'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_alt_result',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_ast_result'.
  $field_bases['field_ast_result'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ast_result',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_beverages_per_week'.
  $field_bases['field_beverages_per_week'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_beverages_per_week',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'number_integer',
  );

  // Exported field_base: 'field_bun_result'.
  $field_bases['field_bun_result'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_bun_result',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_causing_hypertension'.
  $field_bases['field_causing_hypertension'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_causing_hypertension',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'oestrogens' => 'Oestrogens',
        'steroids' => 'Steroids',
        'amitriptyline' => 'Amitriptyline',
        'ibuprofen' => 'Ibuprofen',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_cigarettes_per_week'.
  $field_bases['field_cigarettes_per_week'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_cigarettes_per_week',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'number_integer',
  );

  // Exported field_base: 'field_comorbidities'.
  $field_bases['field_comorbidities'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_comorbidities',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'hiv' => 'HIV',
        'diabetes' => 'Diabetes',
        'kidney-disease' => 'Kidney Disease',
        'pregnancy' => 'Pregnancy',
        'hypertension' => 'Hypertension',
        'gestational-diabetes' => 'Gestational Diabetes',
        'pregnancy-related-hypertension' => 'Pregnancy related Hypertension',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_creatinine_result'.
  $field_bases['field_creatinine_result'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_creatinine_result',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_diabetes_predecessors'.
  $field_bases['field_diabetes_predecessors'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_diabetes_predecessors',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'father' => 'Father',
        'mother' => 'Mother',
        'grand-father' => 'Grand Father',
        'grand-mother' => 'Grand Mother',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_food_group'.
  $field_bases['field_food_group'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_food_group',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'vegetables' => 'Vegetables',
        'carbohydrates' => 'Carbohydrates',
        'protein' => 'Protein',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_hba1c_result'.
  $field_bases['field_hba1c_result'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_hba1c_result',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_hdl_cholesterol'.
  $field_bases['field_hdl_cholesterol'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_hdl_cholesterol',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_heart_problem_predecessors'.
  $field_bases['field_heart_problem_predecessors'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_heart_problem_predecessors',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'father' => 'Father',
        'mother' => 'Mother',
        'grand-father' => 'Grand Father',
        'grand-mother' => 'Grand Mother',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_hypertension_predecessors'.
  $field_bases['field_hypertension_predecessors'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_hypertension_predecessors',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'father' => 'Father',
        'mother' => 'Mother',
        'grand-father' => 'Grand Father',
        'grand-mother' => 'Grand Mother',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ldl_cholesterol'.
  $field_bases['field_ldl_cholesterol'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ldl_cholesterol',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_medical_conditions'.
  $field_bases['field_medical_conditions'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_medical_conditions',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'hiv' => 'HIV',
        'diabetes' => 'Diabetes',
        'pregnancy' => 'Pregnancy',
        'hypertension' => 'Hypertension',
        'neuropathy' => 'Neuropathy',
        'rental-complications' => 'Rental complications',
        'malaria' => 'Malaria',
        'tuberculosis' => 'Tuberculosis',
        'hepatitis-b' => 'Hepatitis B',
        'syphilis' => 'Syphilis',
        'eye-complications' => 'Eye complications',
        'anemia' => 'Anemia',
        'other' => 'Other',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_danger_signs'.
  $field_bases['field_ncd_danger_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_danger_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'dyspnea' => 'Acute Shortness of Breath (Dyspnea)',
        'vision-changes' => 'Vision Changes',
        'chest-pain' => 'Chest Pain',
        'flank-pain' => 'Flank Pain',
        'hematuria' => 'Blood in Urine (Hematuria)',
        'severe-headaches' => 'Severe Headaches',
        'loss-of-conciousness' => 'Loss of Conciousness Since Last Visit',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_diagnoses'.
  $field_bases['field_ncd_diagnoses'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_diagnoses',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'hypertension-stage1' => 'Stage 1 Hypertension',
        'hypertension-stage2' => 'Stage 2 Hypertension',
        'hypertension-stage3' => 'Stage 3 Hypertension',
        'diabetes-initial' => 'Diabetes on inital phase of encounter',
        'diabetes-recurrent' => 'Diabetes on recurrent phase of encounter',
        'renal-complications' => 'Renal Complications',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_encounter'.
  $field_bases['field_ncd_encounter'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_encounter',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'ncd_encounter' => 'ncd_encounter',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_ncd_family_history_signs'.
  $field_bases['field_ncd_family_history_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_family_history_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'hypertension-history' => 'Hypertension History',
        'heart-problem-history' => 'Heart Problem History',
        'diabetes-history' => 'Diabetes History',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_group1_symptoms'.
  $field_bases['field_ncd_group1_symptoms'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_group1_symptoms',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'swelling-in-legs' => 'Swelling in Legs',
        'urinary-frequency' => 'Urinary Frequency',
        'anxiety' => 'Anxiety',
        'weight-loss' => 'Weight Loss',
        'palpitations' => 'Palpitations',
        'tremor' => 'Tremor',
        'swelling-in-face' => 'Swelling in Face',
        'swelling-in-abdomen' => 'Swelling in Abdomen',
        'dizziness-with-changing-position' => 'Dizziness with Changing Position',
        'mild-headache' => 'Mild Headache',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_group2_symptoms'.
  $field_bases['field_ncd_group2_symptoms'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_group2_symptoms',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'weakness-of-one-side-of-the-body' => 'Weakness of One Side of the Body',
        'problems-with-walking' => 'Problems with Walking',
        'problems-with-talking' => 'Problems with Talking',
        'decreased-vision' => 'Decreased Vision',
        'blurry-vision' => 'lurry Vision',
        'increased-fatigue-with-daily-activities' => 'Increased Fatigue with Daily Activities',
        'short-of-breath-when-laying-down' => 'Short of Breath When Laying Down',
        'short-of-breath-at-night' => 'Short of Breath at Night',
        'kidney-problems' => 'Kidney Problems',
        'increased-thirst' => 'Increased Thirst',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_guidance'.
  $field_bases['field_ncd_guidance'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_guidance',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'return-1m' => 'Return in one month',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_health_education_signs'.
  $field_bases['field_ncd_health_education_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_health_education_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'hypertension' => 'hypertension',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_pain_symptoms'.
  $field_bases['field_ncd_pain_symptoms'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_pain_symptoms',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'flank' => 'Flank',
        'lower-back' => 'Lower Back',
        'feet' => 'Feet',
        'neck' => 'Neck',
        'abdomen' => 'Abdomen',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ncd_social_history_signs'.
  $field_bases['field_ncd_social_history_signs'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ncd_social_history_signs',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'drink-alcohol' => 'Drink Alcohol',
        'smoke-cigarettes' => 'Smoke Cigarettes',
        'consume-salt' => 'Consume Salt',
        'difficult-4-times-a-year' => 'Difficult to come 4 times a year to health center',
        'help-with-treatment-at-home' => 'People at home to help with treatment',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_total_cholesterol'.
  $field_bases['field_total_cholesterol'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_total_cholesterol',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_treating_diabetes'.
  $field_bases['field_treating_diabetes'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_treating_diabetes',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'metformin' => 'Metformin',
        'glibenclamide' => 'Glibenclamide',
        'insulin' => 'Insulin',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_treating_hypertension'.
  $field_bases['field_treating_hypertension'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_treating_hypertension',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'ace-inhibitors' => 'Ace Inhibitors',
        'arbs' => 'ARBs',
        'hctz' => 'HCTZ',
        'calcium-channel-blockers' => 'Calcium Channel Blockers',
        'methyldopa' => 'Methyldopa',
        'beta-blockers' => 'BetaBlockers',
        'hydralazine' => 'Hydralazine',
        'none' => 'None',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_triglycerides'.
  $field_bases['field_triglycerides'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_triglycerides',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'number',
    'settings' => array(
      'decimal_separator' => '.',
    ),
    'translatable' => 0,
    'type' => 'number_float',
  );

  // Exported field_base: 'field_unit_of_measurement'.
  $field_bases['field_unit_of_measurement'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_unit_of_measurement',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'mmol-L' => 'mmol/L',
        'mg-dL' => 'mg/dL',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
