<?php

/**
 * @file
 * Code for the Hedley Activity feature.
 */

include_once 'hedley_activity.features.inc';

// Define the measurements content types.
define('HEDLEY_ACTIVITY_ATTENDANCE_CONTENT_TYPE', 'attendance');
define('HEDLEY_ACTIVITY_FAMILY_PLANNING_CONTENT_TYPE', 'family_planning');
define('HEDLEY_ACTIVITY_HEIGHT_CONTENT_TYPE', 'height');
define('HEDLEY_ACTIVITY_MUAC_CONTENT_TYPE', 'muac');
define('HEDLEY_ACTIVITY_NUTRITION_CONTENT_TYPE', 'nutrition');
define('HEDLEY_ACTIVITY_PHOTO_CONTENT_TYPE', 'photo');
define('HEDLEY_ACTIVITY_WEIGHT_CONTENT_TYPE', 'weight');

/**
 * Get the measurements content types.
 *
 * @return array
 *   All the measurements content types.
 */
function hedley_activity_get_measurements_content_types() {
  return [
    HEDLEY_ACTIVITY_ATTENDANCE_CONTENT_TYPE,
    HEDLEY_ACTIVITY_FAMILY_PLANNING_CONTENT_TYPE,
    HEDLEY_ACTIVITY_HEIGHT_CONTENT_TYPE,
    HEDLEY_ACTIVITY_MUAC_CONTENT_TYPE,
    HEDLEY_ACTIVITY_NUTRITION_CONTENT_TYPE,
    HEDLEY_ACTIVITY_PHOTO_CONTENT_TYPE,
    HEDLEY_ACTIVITY_WEIGHT_CONTENT_TYPE,
  ];
}

/**
 * Implements hook_node_insert().
 */
function hedley_activity_node_insert($node) {
  if ($node->type != 'height') {
    return;
  }

  // Make sure we get updated data.
  entity_get_controller('node')->resetCache([$node->nid]);
  hedley_activity_handle_height($node->nid);
}

/**
 * Implements hook_node_update().
 */
function hedley_activity_node_update($node) {
  if (!in_array($node->type, ['person', 'height'])) {
    return;
  }

  // Make sure we get updated data.
  entity_get_controller('node')->resetCache([$node->nid]);

  if ($node->type == 'person') {
    // Recalculate z-score values when gender or birth date changes.
    $wrapper = entity_metadata_wrapper('node', $node);
    $wrapper_orig = entity_metadata_wrapper('node', $node->original);

    $birth_date = $wrapper->field_birth_date->value();
    $birth_date_orig = $wrapper_orig->field_birth_date->value();
    $gender = $wrapper->field_gender->value();
    $gender_orig = $wrapper_orig->field_gender->value();

    if ($birth_date !== $birth_date_orig || $gender !== $gender_orig) {
      hedley_activity_handle_child_zscores($node->nid);
    }

    return;
  }

  if ($node->type == 'height') {
    hedley_activity_handle_height($node->nid);
    return;
  }
}

/**
 * Given the node ID of a `height`, update z-score for related weight.
 *
 * @param int $nid
 *   The node ID of the height.
 */
function hedley_activity_handle_height($nid) {
  $height = entity_metadata_wrapper('node', $nid);

  $session_id = $height->field_session->getIdentifier();
  $child_id = $height->field_person->getIdentifier();

  $weight_id = hedley_activity_weight_for_session($session_id, $child_id);

  if (empty($weight_id)) {
    // There is no weight node for this child/session combination.
    return;
  }

  $weight = entity_metadata_wrapper('node', $weight_id);

  // The presave should fill it in, so no need to think too hard here ...
  $weight->field_zscore_length->set(NULL);
  $weight->field_zscore_bmi->set(NULL);
  $weight->field_bmi->set(NULL);
  $weight->save();
}

/**
 * Given the node ID of a `child`, update all z-scores for the child.
 *
 * @param int $nid
 *   The node ID of the child.
 */
function hedley_activity_handle_child_zscores($nid) {
  $batch_size = 50;
  $offset = 0;

  $base_query = new EntityFieldQuery();
  $base_query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', ['height', 'weight'], 'IN')
    ->fieldCondition('field_person', 'target_id', $nid)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyOrderBy('nid', 'ASC');

  $query_count = clone $base_query;
  $count = $query_count->count()->execute();

  while ($offset < $count) {
    $query = clone $base_query;

    $result = $query
      ->range($offset, $batch_size)
      ->execute();

    if (empty($result['node'])) {
      // No more z-scores need updating.
      return;
    }

    $keys = array_keys($result['node']);
    node_load_multiple($keys);

    foreach ($keys as $key) {
      // Just trigger presave ... that will do the hard work!
      $wrapper = entity_metadata_wrapper('node', $key);
      $wrapper->field_zscore_age->set(NULL);
      $wrapper->save();
    }

    $offset += $batch_size;

    // Free up memory.
    drupal_static_reset();
  }
}

/**
 * Implements hook_node_presave().
 *
 * Calculate z-scores for measurements.
 */
function hedley_activity_node_presave($node) {
  if (!in_array($node->type, ['height', 'weight'])) {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);

  if (empty($wrapper->field_person->value())) {
    // We need the child for birthdate and gender ...
    return;
  }

  $birth = $wrapper->field_person->field_birth_date->value();
  $gender = $wrapper->field_person->field_gender->value();
  $measured = $wrapper->field_date_measured->value();

  // 86400 seconds in a day.
  $days = ($measured - $birth) / 86400;

  if ($node->type == 'height') {
    $zscore = hedley_zscore_length_for_age($days, $gender, $wrapper->field_height->value());
    $wrapper->field_zscore_age->set($zscore);
    return;
  }

  if ($node->type == 'weight') {
    $zscore_for_age = hedley_zscore_weight_for_age($days, $gender, $wrapper->field_weight->value());
    $wrapper->field_zscore_age->set($zscore_for_age);

    $child_id = $wrapper->field_person->getIdentifier();
    $session_id = $wrapper->field_session->getIdentifier();

    $height_id = hedley_activity_height_for_session($session_id, $child_id);

    if (empty($height_id)) {
      // No height yet, so no zscore_length or BMI.
      $wrapper->field_zscore_length->set(NULL);
      $wrapper->field_zscore_bmi->set(NULL);
      $wrapper->field_bmi->set(NULL);
    }
    else {
      $height = entity_metadata_wrapper('node', $height_id);
      $cm = $height->field_height->value();
      $kg = $wrapper->field_weight->value();

      // For children older than two, we actually measure height rather than
      // length. So, we need to use the weight-for-height tables, rather than
      // weight-for-length. But we store the result in the same field.
      if ($days > (365 * 2)) {
        $zscore_for_length = hedley_zscore_weight_for_height($cm, $gender, $kg);
      }
      else {
        $zscore_for_length = hedley_zscore_weight_for_length($cm, $gender, $kg);
      }

      // The formula is (kg / meters squared).
      $bmi = $kg / pow($cm / 100, 2);
      $zscore_bmi_for_age = hedley_zscore_bmi_for_age($days, $gender, $bmi);

      $wrapper->field_zscore_length->set($zscore_for_length);
      $wrapper->field_zscore_bmi->set($zscore_bmi_for_age);
      $wrapper->field_bmi->set($bmi);
    }
  }
}

/**
 * Get the height for a child in a session.
 *
 * @param int $session_id
 *   The node ID of the session.
 * @param int $child_id
 *   The node ID of the child.
 *
 * @return int|null
 *   The node ID of the height node, or NULL.
 */
function hedley_activity_height_for_session($session_id, $child_id) {
  if (empty($session_id) || empty($child_id)) {
    return NULL;
  }

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'height')
    ->fieldCondition('field_session', 'target_id', $session_id)
    ->fieldCondition('field_person', 'target_id', $child_id)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->range(0, 1)
    ->execute();

  return !empty($result['node']) ? key($result['node']) : NULL;
}

/**
 * Get the weight for a child in a session.
 *
 * @param int $session_id
 *   The node ID of the session.
 * @param int $child_id
 *   The node ID of the child.
 *
 * @return int|null
 *   The node ID of the weight node, or NULL.
 */
function hedley_activity_weight_for_session($session_id, $child_id) {
  if (empty($session_id) || empty($child_id)) {
    return NULL;
  }

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'weight')
    ->fieldCondition('field_session', 'target_id', $session_id)
    ->fieldCondition('field_person', 'target_id', $child_id)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->range(0, 1)
    ->execute();

  return !empty($result['node']) ? key($result['node']) : NULL;
}

/**
 * Get a measurement by the measurement types and period.
 *
 * @param int $person_id
 *   The person node ID.
 * @param array $measurement_bundles
 *   The measurement node bundle.
 * @param array $period
 *   The period of the measurement, contains a start and an end.
 * @param int $range
 *   Optional; The query's range.
 *
 * @return array
 *   Node IDs if they exist or empty array if no nodes exist.
 */
function hedley_activity_get_measurements_by_period($person_id, array $measurement_bundles, array $period, $range = 100) {
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $measurement_bundles, 'IN')
    ->fieldCondition('field_person', 'target_id', $person_id)
    ->fieldCondition('field_date_measured', 'value', [
      date('Y-m-d 00:00:00', $period['start']),
      date('Y-m-d 00:00:00', $period['end']),
    ], 'BETWEEN')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->range(0, $range)
    ->execute();

  return !empty($result['node']) ? array_keys($result['node']) : [];
}

/**
 * Get an attendance by the session and the person IDs.
 *
 * @param int $session_id
 *   The session node ID.
 * @param int $person_id
 *   Optional; The person node ID.
 * @param bool $attendance_status
 *   Optional; The attendance status.
 * @param int $range
 *   Optional; The query's range.
 *
 * @return array
 *   Node IDs if they exist or empty array if no nodes exist.
 */
function hedley_activity_get_attendance_by_session($session_id, $person_id = NULL, $attendance_status = TRUE, $range = 100) {
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'attendance')
    ->fieldCondition('field_session', 'target_id', $session_id)
    ->fieldCondition('field_attended', 'value', $attendance_status)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->range(0, $range);

  if ($person_id) {
    $query
      ->fieldCondition('field_person', 'target_id', $person_id);
  }

  $result = $query->execute();

  return !empty($result['node']) ? array_keys($result['node']) : [];
}
