<?php

/**
 * @file
 * Code for the Hedley Activity feature.
 */

include_once 'hedley_activity.features.inc';

/**
 * Return the activity related node types and RESTful resource handler name.
 *
 * @return array
 *   Array keyed by the node type machine name, and the RESTful resource handler
 *   name as value.
 */
function hedley_activity_get_activity_node_types_and_restful_name() {
  return [
    'height' => 'heights',
    'weight' => 'weights',
  ];
}

/**
 * Implements hook_node_insert().
 */
function hedley_activity_node_insert($node) {
  hedley_activity_trigger_pusher_on_item_data_change($node);
}

/**
 * Implements hook_node_update().
 */
function hedley_activity_node_update($node) {
  if (!in_array($node->type, array_keys(hedley_activity_get_activity_node_types_and_restful_name()))) {
    return;
  }
  // Make sure we get updated data.
  entity_get_controller('node')->resetCache();
  hedley_activity_trigger_pusher_on_item_data_change($node);
}

/**
 * Trigger a pusher event for a Item data.
 *
 * @param object $node
 *   A Item data node type.
 */
function hedley_activity_trigger_pusher_on_item_data_change($node) {
  if (!in_array($node->type, array_keys(hedley_activity_get_activity_node_types_and_restful_name()))) {
    return;
  }

  if ($node->status == NODE_NOT_PUBLISHED) {
    // Node is not published.
    return;
  }

  $account = user_load($node->uid);

  $handler_names = hedley_activity_get_activity_node_types_and_restful_name();

  $handler = restful_get_restful_handler($handler_names[$node->type]);
  $handler->setAccount($account);
  $data = $handler->get($node->nid);

  $event_name = 'activity__update';

  hedley_pusher_trigger_event('general', $event_name, $data[0]);
}

/**
 * Implements hook_permission().
 */
function hedley_activity_permission() {
  return [
    'manage unpublished measurement node' => [
      'title' => t('Manage unpublished measurement node'),
      'description' => t('Manage unpublished measurement node: height, weight and MUAC'),
    ],
  ];
}

/**
 * Implements hook_node_access().
 */
function hedley_activity_node_access($node, $op, $account) {

  $type = is_object($node) ? $node->type : $node;

  if (!in_array($type, ['weight', 'height', 'muac'])) {
    // Not a measurement node. Skipping.
    return NODE_ACCESS_IGNORE;
  }

  $wrapper = entity_metadata_wrapper('node', $node);

  if ($wrapper->field_activity_status->value() == 'completed') {
    // The status is completed, that's OK.
    return NODE_ACCESS_IGNORE;
  }

  // Check if the user has a permission to unpublished measurement nodes.
  return user_access('manage unpublished measurement node', $account) ? NODE_ACCESS_ALLOW : NODE_ACCESS_DENY;
}
