<?php

/**
 * @file
 * hedley_well_child.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function hedley_well_child_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'create well_child_albendazole content'.
  $permissions['create well_child_albendazole content'] = array(
    'name' => 'create well_child_albendazole content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_bcg_immunisation content'.
  $permissions['create well_child_bcg_immunisation content'] = array(
    'name' => 'create well_child_bcg_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_caring content'.
  $permissions['create well_child_caring content'] = array(
    'name' => 'create well_child_caring content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_contributing_factors content'.
  $permissions['create well_child_contributing_factors content'] = array(
    'name' => 'create well_child_contributing_factors content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_dtp_immunisation content'.
  $permissions['create well_child_dtp_immunisation content'] = array(
    'name' => 'create well_child_dtp_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_dtp_sa_immunisation content'.
  $permissions['create well_child_dtp_sa_immunisation content'] = array(
    'name' => 'create well_child_dtp_sa_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_ecd content'.
  $permissions['create well_child_ecd content'] = array(
    'name' => 'create well_child_ecd content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_encounter content'.
  $permissions['create well_child_encounter content'] = array(
    'name' => 'create well_child_encounter content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_feeding content'.
  $permissions['create well_child_feeding content'] = array(
    'name' => 'create well_child_feeding content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_follow_up content'.
  $permissions['create well_child_follow_up content'] = array(
    'name' => 'create well_child_follow_up content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_food_security content'.
  $permissions['create well_child_food_security content'] = array(
    'name' => 'create well_child_food_security content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_head_circumference content'.
  $permissions['create well_child_head_circumference content'] = array(
    'name' => 'create well_child_head_circumference content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_health_education content'.
  $permissions['create well_child_health_education content'] = array(
    'name' => 'create well_child_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_height content'.
  $permissions['create well_child_height content'] = array(
    'name' => 'create well_child_height content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_hpv_immunisation content'.
  $permissions['create well_child_hpv_immunisation content'] = array(
    'name' => 'create well_child_hpv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_hygiene content'.
  $permissions['create well_child_hygiene content'] = array(
    'name' => 'create well_child_hygiene content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_ipv_immunisation content'.
  $permissions['create well_child_ipv_immunisation content'] = array(
    'name' => 'create well_child_ipv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_mebendezole content'.
  $permissions['create well_child_mebendezole content'] = array(
    'name' => 'create well_child_mebendezole content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_mr_immunisation content'.
  $permissions['create well_child_mr_immunisation content'] = array(
    'name' => 'create well_child_mr_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_muac content'.
  $permissions['create well_child_muac content'] = array(
    'name' => 'create well_child_muac content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_ncda content'.
  $permissions['create well_child_ncda content'] = array(
    'name' => 'create well_child_ncda content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_next_visit content'.
  $permissions['create well_child_next_visit content'] = array(
    'name' => 'create well_child_next_visit content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_nutrition content'.
  $permissions['create well_child_nutrition content'] = array(
    'name' => 'create well_child_nutrition content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_opv_immunisation content'.
  $permissions['create well_child_opv_immunisation content'] = array(
    'name' => 'create well_child_opv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_pcv13_immunisation content'.
  $permissions['create well_child_pcv13_immunisation content'] = array(
    'name' => 'create well_child_pcv13_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_photo content'.
  $permissions['create well_child_photo content'] = array(
    'name' => 'create well_child_photo content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_pregnancy_summary content'.
  $permissions['create well_child_pregnancy_summary content'] = array(
    'name' => 'create well_child_pregnancy_summary content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_rotarix_immunisation content'.
  $permissions['create well_child_rotarix_immunisation content'] = array(
    'name' => 'create well_child_rotarix_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_send_to_hc content'.
  $permissions['create well_child_send_to_hc content'] = array(
    'name' => 'create well_child_send_to_hc content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_symptoms_review content'.
  $permissions['create well_child_symptoms_review content'] = array(
    'name' => 'create well_child_symptoms_review content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_vitals content'.
  $permissions['create well_child_vitals content'] = array(
    'name' => 'create well_child_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_vitamin_a content'.
  $permissions['create well_child_vitamin_a content'] = array(
    'name' => 'create well_child_vitamin_a content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'create well_child_weight content'.
  $permissions['create well_child_weight content'] = array(
    'name' => 'create well_child_weight content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_albendazole content'.
  $permissions['delete any well_child_albendazole content'] = array(
    'name' => 'delete any well_child_albendazole content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_bcg_immunisation content'.
  $permissions['delete any well_child_bcg_immunisation content'] = array(
    'name' => 'delete any well_child_bcg_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_caring content'.
  $permissions['delete any well_child_caring content'] = array(
    'name' => 'delete any well_child_caring content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_contributing_factors content'.
  $permissions['delete any well_child_contributing_factors content'] = array(
    'name' => 'delete any well_child_contributing_factors content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_dtp_immunisation content'.
  $permissions['delete any well_child_dtp_immunisation content'] = array(
    'name' => 'delete any well_child_dtp_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_dtp_sa_immunisation content'.
  $permissions['delete any well_child_dtp_sa_immunisation content'] = array(
    'name' => 'delete any well_child_dtp_sa_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_ecd content'.
  $permissions['delete any well_child_ecd content'] = array(
    'name' => 'delete any well_child_ecd content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_encounter content'.
  $permissions['delete any well_child_encounter content'] = array(
    'name' => 'delete any well_child_encounter content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_feeding content'.
  $permissions['delete any well_child_feeding content'] = array(
    'name' => 'delete any well_child_feeding content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_follow_up content'.
  $permissions['delete any well_child_follow_up content'] = array(
    'name' => 'delete any well_child_follow_up content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_food_security content'.
  $permissions['delete any well_child_food_security content'] = array(
    'name' => 'delete any well_child_food_security content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_head_circumference content'.
  $permissions['delete any well_child_head_circumference content'] = array(
    'name' => 'delete any well_child_head_circumference content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_health_education content'.
  $permissions['delete any well_child_health_education content'] = array(
    'name' => 'delete any well_child_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_height content'.
  $permissions['delete any well_child_height content'] = array(
    'name' => 'delete any well_child_height content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_hpv_immunisation content'.
  $permissions['delete any well_child_hpv_immunisation content'] = array(
    'name' => 'delete any well_child_hpv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_hygiene content'.
  $permissions['delete any well_child_hygiene content'] = array(
    'name' => 'delete any well_child_hygiene content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_ipv_immunisation content'.
  $permissions['delete any well_child_ipv_immunisation content'] = array(
    'name' => 'delete any well_child_ipv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_mebendezole content'.
  $permissions['delete any well_child_mebendezole content'] = array(
    'name' => 'delete any well_child_mebendezole content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_mr_immunisation content'.
  $permissions['delete any well_child_mr_immunisation content'] = array(
    'name' => 'delete any well_child_mr_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_muac content'.
  $permissions['delete any well_child_muac content'] = array(
    'name' => 'delete any well_child_muac content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_ncda content'.
  $permissions['delete any well_child_ncda content'] = array(
    'name' => 'delete any well_child_ncda content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_next_visit content'.
  $permissions['delete any well_child_next_visit content'] = array(
    'name' => 'delete any well_child_next_visit content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_nutrition content'.
  $permissions['delete any well_child_nutrition content'] = array(
    'name' => 'delete any well_child_nutrition content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_opv_immunisation content'.
  $permissions['delete any well_child_opv_immunisation content'] = array(
    'name' => 'delete any well_child_opv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_pcv13_immunisation content'.
  $permissions['delete any well_child_pcv13_immunisation content'] = array(
    'name' => 'delete any well_child_pcv13_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_photo content'.
  $permissions['delete any well_child_photo content'] = array(
    'name' => 'delete any well_child_photo content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_pregnancy_summary content'.
  $permissions['delete any well_child_pregnancy_summary content'] = array(
    'name' => 'delete any well_child_pregnancy_summary content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_rotarix_immunisation content'.
  $permissions['delete any well_child_rotarix_immunisation content'] = array(
    'name' => 'delete any well_child_rotarix_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_send_to_hc content'.
  $permissions['delete any well_child_send_to_hc content'] = array(
    'name' => 'delete any well_child_send_to_hc content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_symptoms_review content'.
  $permissions['delete any well_child_symptoms_review content'] = array(
    'name' => 'delete any well_child_symptoms_review content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_vitals content'.
  $permissions['delete any well_child_vitals content'] = array(
    'name' => 'delete any well_child_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_vitamin_a content'.
  $permissions['delete any well_child_vitamin_a content'] = array(
    'name' => 'delete any well_child_vitamin_a content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete any well_child_weight content'.
  $permissions['delete any well_child_weight content'] = array(
    'name' => 'delete any well_child_weight content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_albendazole content'.
  $permissions['delete own well_child_albendazole content'] = array(
    'name' => 'delete own well_child_albendazole content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_bcg_immunisation content'.
  $permissions['delete own well_child_bcg_immunisation content'] = array(
    'name' => 'delete own well_child_bcg_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_caring content'.
  $permissions['delete own well_child_caring content'] = array(
    'name' => 'delete own well_child_caring content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_contributing_factors content'.
  $permissions['delete own well_child_contributing_factors content'] = array(
    'name' => 'delete own well_child_contributing_factors content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_dtp_immunisation content'.
  $permissions['delete own well_child_dtp_immunisation content'] = array(
    'name' => 'delete own well_child_dtp_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_dtp_sa_immunisation content'.
  $permissions['delete own well_child_dtp_sa_immunisation content'] = array(
    'name' => 'delete own well_child_dtp_sa_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_ecd content'.
  $permissions['delete own well_child_ecd content'] = array(
    'name' => 'delete own well_child_ecd content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_encounter content'.
  $permissions['delete own well_child_encounter content'] = array(
    'name' => 'delete own well_child_encounter content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_feeding content'.
  $permissions['delete own well_child_feeding content'] = array(
    'name' => 'delete own well_child_feeding content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_follow_up content'.
  $permissions['delete own well_child_follow_up content'] = array(
    'name' => 'delete own well_child_follow_up content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_food_security content'.
  $permissions['delete own well_child_food_security content'] = array(
    'name' => 'delete own well_child_food_security content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_head_circumference content'.
  $permissions['delete own well_child_head_circumference content'] = array(
    'name' => 'delete own well_child_head_circumference content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_health_education content'.
  $permissions['delete own well_child_health_education content'] = array(
    'name' => 'delete own well_child_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_height content'.
  $permissions['delete own well_child_height content'] = array(
    'name' => 'delete own well_child_height content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_hpv_immunisation content'.
  $permissions['delete own well_child_hpv_immunisation content'] = array(
    'name' => 'delete own well_child_hpv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_hygiene content'.
  $permissions['delete own well_child_hygiene content'] = array(
    'name' => 'delete own well_child_hygiene content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_ipv_immunisation content'.
  $permissions['delete own well_child_ipv_immunisation content'] = array(
    'name' => 'delete own well_child_ipv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_mebendezole content'.
  $permissions['delete own well_child_mebendezole content'] = array(
    'name' => 'delete own well_child_mebendezole content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_mr_immunisation content'.
  $permissions['delete own well_child_mr_immunisation content'] = array(
    'name' => 'delete own well_child_mr_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_muac content'.
  $permissions['delete own well_child_muac content'] = array(
    'name' => 'delete own well_child_muac content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_ncda content'.
  $permissions['delete own well_child_ncda content'] = array(
    'name' => 'delete own well_child_ncda content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_next_visit content'.
  $permissions['delete own well_child_next_visit content'] = array(
    'name' => 'delete own well_child_next_visit content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_nutrition content'.
  $permissions['delete own well_child_nutrition content'] = array(
    'name' => 'delete own well_child_nutrition content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_opv_immunisation content'.
  $permissions['delete own well_child_opv_immunisation content'] = array(
    'name' => 'delete own well_child_opv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_pcv13_immunisation content'.
  $permissions['delete own well_child_pcv13_immunisation content'] = array(
    'name' => 'delete own well_child_pcv13_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_photo content'.
  $permissions['delete own well_child_photo content'] = array(
    'name' => 'delete own well_child_photo content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_pregnancy_summary content'.
  $permissions['delete own well_child_pregnancy_summary content'] = array(
    'name' => 'delete own well_child_pregnancy_summary content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_rotarix_immunisation content'.
  $permissions['delete own well_child_rotarix_immunisation content'] = array(
    'name' => 'delete own well_child_rotarix_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_send_to_hc content'.
  $permissions['delete own well_child_send_to_hc content'] = array(
    'name' => 'delete own well_child_send_to_hc content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_symptoms_review content'.
  $permissions['delete own well_child_symptoms_review content'] = array(
    'name' => 'delete own well_child_symptoms_review content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_vitals content'.
  $permissions['delete own well_child_vitals content'] = array(
    'name' => 'delete own well_child_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_vitamin_a content'.
  $permissions['delete own well_child_vitamin_a content'] = array(
    'name' => 'delete own well_child_vitamin_a content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'delete own well_child_weight content'.
  $permissions['delete own well_child_weight content'] = array(
    'name' => 'delete own well_child_weight content',
    'roles' => array(
      'administrator' => 'administrator',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_albendazole content'.
  $permissions['edit any well_child_albendazole content'] = array(
    'name' => 'edit any well_child_albendazole content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_bcg_immunisation content'.
  $permissions['edit any well_child_bcg_immunisation content'] = array(
    'name' => 'edit any well_child_bcg_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_caring content'.
  $permissions['edit any well_child_caring content'] = array(
    'name' => 'edit any well_child_caring content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_contributing_factors content'.
  $permissions['edit any well_child_contributing_factors content'] = array(
    'name' => 'edit any well_child_contributing_factors content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_dtp_immunisation content'.
  $permissions['edit any well_child_dtp_immunisation content'] = array(
    'name' => 'edit any well_child_dtp_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_dtp_sa_immunisation content'.
  $permissions['edit any well_child_dtp_sa_immunisation content'] = array(
    'name' => 'edit any well_child_dtp_sa_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_ecd content'.
  $permissions['edit any well_child_ecd content'] = array(
    'name' => 'edit any well_child_ecd content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_encounter content'.
  $permissions['edit any well_child_encounter content'] = array(
    'name' => 'edit any well_child_encounter content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_feeding content'.
  $permissions['edit any well_child_feeding content'] = array(
    'name' => 'edit any well_child_feeding content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_follow_up content'.
  $permissions['edit any well_child_follow_up content'] = array(
    'name' => 'edit any well_child_follow_up content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_food_security content'.
  $permissions['edit any well_child_food_security content'] = array(
    'name' => 'edit any well_child_food_security content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_head_circumference content'.
  $permissions['edit any well_child_head_circumference content'] = array(
    'name' => 'edit any well_child_head_circumference content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_health_education content'.
  $permissions['edit any well_child_health_education content'] = array(
    'name' => 'edit any well_child_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_height content'.
  $permissions['edit any well_child_height content'] = array(
    'name' => 'edit any well_child_height content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_hpv_immunisation content'.
  $permissions['edit any well_child_hpv_immunisation content'] = array(
    'name' => 'edit any well_child_hpv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_hygiene content'.
  $permissions['edit any well_child_hygiene content'] = array(
    'name' => 'edit any well_child_hygiene content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_ipv_immunisation content'.
  $permissions['edit any well_child_ipv_immunisation content'] = array(
    'name' => 'edit any well_child_ipv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_mebendezole content'.
  $permissions['edit any well_child_mebendezole content'] = array(
    'name' => 'edit any well_child_mebendezole content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_mr_immunisation content'.
  $permissions['edit any well_child_mr_immunisation content'] = array(
    'name' => 'edit any well_child_mr_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_muac content'.
  $permissions['edit any well_child_muac content'] = array(
    'name' => 'edit any well_child_muac content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_ncda content'.
  $permissions['edit any well_child_ncda content'] = array(
    'name' => 'edit any well_child_ncda content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_next_visit content'.
  $permissions['edit any well_child_next_visit content'] = array(
    'name' => 'edit any well_child_next_visit content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_nutrition content'.
  $permissions['edit any well_child_nutrition content'] = array(
    'name' => 'edit any well_child_nutrition content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_opv_immunisation content'.
  $permissions['edit any well_child_opv_immunisation content'] = array(
    'name' => 'edit any well_child_opv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_pcv13_immunisation content'.
  $permissions['edit any well_child_pcv13_immunisation content'] = array(
    'name' => 'edit any well_child_pcv13_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_photo content'.
  $permissions['edit any well_child_photo content'] = array(
    'name' => 'edit any well_child_photo content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_pregnancy_summary content'.
  $permissions['edit any well_child_pregnancy_summary content'] = array(
    'name' => 'edit any well_child_pregnancy_summary content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_rotarix_immunisation content'.
  $permissions['edit any well_child_rotarix_immunisation content'] = array(
    'name' => 'edit any well_child_rotarix_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_send_to_hc content'.
  $permissions['edit any well_child_send_to_hc content'] = array(
    'name' => 'edit any well_child_send_to_hc content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_symptoms_review content'.
  $permissions['edit any well_child_symptoms_review content'] = array(
    'name' => 'edit any well_child_symptoms_review content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_vitals content'.
  $permissions['edit any well_child_vitals content'] = array(
    'name' => 'edit any well_child_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_vitamin_a content'.
  $permissions['edit any well_child_vitamin_a content'] = array(
    'name' => 'edit any well_child_vitamin_a content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit any well_child_weight content'.
  $permissions['edit any well_child_weight content'] = array(
    'name' => 'edit any well_child_weight content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_albendazole content'.
  $permissions['edit own well_child_albendazole content'] = array(
    'name' => 'edit own well_child_albendazole content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_bcg_immunisation content'.
  $permissions['edit own well_child_bcg_immunisation content'] = array(
    'name' => 'edit own well_child_bcg_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_caring content'.
  $permissions['edit own well_child_caring content'] = array(
    'name' => 'edit own well_child_caring content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_contributing_factors content'.
  $permissions['edit own well_child_contributing_factors content'] = array(
    'name' => 'edit own well_child_contributing_factors content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_dtp_immunisation content'.
  $permissions['edit own well_child_dtp_immunisation content'] = array(
    'name' => 'edit own well_child_dtp_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_dtp_sa_immunisation content'.
  $permissions['edit own well_child_dtp_sa_immunisation content'] = array(
    'name' => 'edit own well_child_dtp_sa_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_ecd content'.
  $permissions['edit own well_child_ecd content'] = array(
    'name' => 'edit own well_child_ecd content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_encounter content'.
  $permissions['edit own well_child_encounter content'] = array(
    'name' => 'edit own well_child_encounter content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_feeding content'.
  $permissions['edit own well_child_feeding content'] = array(
    'name' => 'edit own well_child_feeding content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_follow_up content'.
  $permissions['edit own well_child_follow_up content'] = array(
    'name' => 'edit own well_child_follow_up content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_food_security content'.
  $permissions['edit own well_child_food_security content'] = array(
    'name' => 'edit own well_child_food_security content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_head_circumference content'.
  $permissions['edit own well_child_head_circumference content'] = array(
    'name' => 'edit own well_child_head_circumference content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_health_education content'.
  $permissions['edit own well_child_health_education content'] = array(
    'name' => 'edit own well_child_health_education content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_height content'.
  $permissions['edit own well_child_height content'] = array(
    'name' => 'edit own well_child_height content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_hpv_immunisation content'.
  $permissions['edit own well_child_hpv_immunisation content'] = array(
    'name' => 'edit own well_child_hpv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_hygiene content'.
  $permissions['edit own well_child_hygiene content'] = array(
    'name' => 'edit own well_child_hygiene content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_ipv_immunisation content'.
  $permissions['edit own well_child_ipv_immunisation content'] = array(
    'name' => 'edit own well_child_ipv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_mebendezole content'.
  $permissions['edit own well_child_mebendezole content'] = array(
    'name' => 'edit own well_child_mebendezole content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_mr_immunisation content'.
  $permissions['edit own well_child_mr_immunisation content'] = array(
    'name' => 'edit own well_child_mr_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_muac content'.
  $permissions['edit own well_child_muac content'] = array(
    'name' => 'edit own well_child_muac content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_ncda content'.
  $permissions['edit own well_child_ncda content'] = array(
    'name' => 'edit own well_child_ncda content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_next_visit content'.
  $permissions['edit own well_child_next_visit content'] = array(
    'name' => 'edit own well_child_next_visit content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_nutrition content'.
  $permissions['edit own well_child_nutrition content'] = array(
    'name' => 'edit own well_child_nutrition content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_opv_immunisation content'.
  $permissions['edit own well_child_opv_immunisation content'] = array(
    'name' => 'edit own well_child_opv_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_pcv13_immunisation content'.
  $permissions['edit own well_child_pcv13_immunisation content'] = array(
    'name' => 'edit own well_child_pcv13_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_photo content'.
  $permissions['edit own well_child_photo content'] = array(
    'name' => 'edit own well_child_photo content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_pregnancy_summary content'.
  $permissions['edit own well_child_pregnancy_summary content'] = array(
    'name' => 'edit own well_child_pregnancy_summary content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_rotarix_immunisation content'.
  $permissions['edit own well_child_rotarix_immunisation content'] = array(
    'name' => 'edit own well_child_rotarix_immunisation content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_send_to_hc content'.
  $permissions['edit own well_child_send_to_hc content'] = array(
    'name' => 'edit own well_child_send_to_hc content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_symptoms_review content'.
  $permissions['edit own well_child_symptoms_review content'] = array(
    'name' => 'edit own well_child_symptoms_review content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_vitals content'.
  $permissions['edit own well_child_vitals content'] = array(
    'name' => 'edit own well_child_vitals content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_vitamin_a content'.
  $permissions['edit own well_child_vitamin_a content'] = array(
    'name' => 'edit own well_child_vitamin_a content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  // Exported permission: 'edit own well_child_weight content'.
  $permissions['edit own well_child_weight content'] = array(
    'name' => 'edit own well_child_weight content',
    'roles' => array(
      'administrator' => 'administrator',
      'sync' => 'sync',
    ),
    'module' => 'node',
  );

  return $permissions;
}
