<?php

/**
 * @file
 * Code for the RESTful integration.
 */

if (!drupal_is_cli()) {
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Credentials: true');
  header('Access-Control-Allow-Headers: Authorization, access-token, Cache-Control, X-Requested-With, Content-Type');
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function hedley_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Convert strings to short form dates.
 *
 * From form "2014-11-13 18:00:00" to
 * preserve just the date part, i.e. "2014-11-13".
 *
 * This is suitable only for values which do not have
 * interesting time zone information ... that is, only
 * for values that represent nominal dates without times.
 *
 * @param string $value
 *   The date string, e.g. "2014-11-13 18:00:00".
 *
 * @return false|string
 *   The date portion only, e.g. "2014-11-13".
 */
function hedley_restful_timestamp_only_date($value) {
  $date = explode(' ', $value);
  return $date[0];
}

/**
 * Given an EntityFieldQuery result, extract the ids, or an empty array.
 *
 * @param array $result
 *   The result of EntityFieldQuery->execute()
 *
 * @return array
 *   An array of node IDs
 */
function hedley_restful_extract_ids(array $result) {
  return empty($result['node']) ? [] : array_keys($result['node']);
}
