#!/bin/bash

## Description: Run robo commands inside the web container for the client app.
## Usage: client-install
## Example: "ddev client-install".
export PATH=~/.nvm/versions/node/v9.0.0/bin:$PATH;

npm install -g bower

cd ../../client
npm install --no-audit --no-fund
bower install
