#!/bin/bash

## Description: Run robo commands inside the web container.
## Usage: robo
## Example: "ddev robo compile:theme" or "ddev robo compile:theme-debug".

cd ..
if [[ ! -f ./vendor/bin/robo ]];
then
  composer install
fi


./vendor/bin/robo $@
