#!/bin/bash

## Description: Run simpletest test suite.
## Usage: simpletest
## Example: "ddev simpletest"
#
drush en simpletest -y
cd ..
php ./www/scripts/run-tests.sh --php "$(which php)" --concurrency 4 --verbose --color --url http://eheza-app.ddev.site:8081 Hedley 2>&1 | tee /tmp/simpletest-result.txt

grep -E -i "([1-9]+ fail)|(Fatal error)|([1-9]+ exception)|([0-9]+0 fail)|([0-9]+0 exception)" /tmp/simpletest-result.txt && exit 1

drush pm-disable simpletest -y

exit 0
