module Backend.PrenatalEncounter.Types exposing (..)


type PrenatalDiagnosis
    = DiagnosisChronicHypertensionImmediate
    | DiagnosisChronicHypertensionAfterRecheck
    | DiagnosisGestationalHypertensionImmediate
    | DiagnosisGestationalHypertensionAfterRecheck
    | DiagnosisModeratePreeclampsiaImmediate
    | DiagnosisModeratePreeclampsiaImmediateEGA37Plus
    | DiagnosisModeratePreeclampsiaAfterRecheck
    | DiagnosisModeratePreeclampsiaAfterRecheckEGA37Plus
    | DiagnosisSeverePreeclampsiaImmediate
    | DiagnosisSeverePreeclampsiaImmediateEGA37Plus
    | DiagnosisSeverePreeclampsiaAfterRecheck
    | DiagnosisSeverePreeclampsiaAfterRecheckEGA37Plus
    | DiagnosisEclampsia
    | DiagnosisHIV
    | DiagnosisHIVDetectableViralLoad
    | DiagnosisDiscordantPartnership
    | DiagnosisSyphilis
    | DiagnosisSyphilisWithComplications
    | DiagnosisNeurosyphilis
    | DiagnosisHepatitisB
    | DiagnosisMalaria
    | DiagnosisMalariaMedicatedContinued
    | DiagnosisMalariaWithAnemia
    | DiagnosisMalariaWithAnemiaMedicatedContinued
    | DiagnosisMalariaWithSevereAnemia
    | DiagnosisModerateAnemia
    | DiagnosisSevereAnemia
    | DiagnosisSevereAnemiaWithComplications
    | DiagnosisMiscarriage
    | DiagnosisMolarPregnancy
    | DiagnosisPlacentaPrevia
    | DiagnosisPlacentalAbruption
    | DiagnosisUterineRupture
    | DiagnosisObstructedLabor
    | DiagnosisPostAbortionSepsis
    | DiagnosisEctopicPregnancy
    | DiagnosisPROM
    | DiagnosisPPROM
    | DiagnosisHyperemesisGravidum
    | DiagnosisHyperemesisGravidumBySymptoms
    | DiagnosisSevereVomiting
    | DiagnosisSevereVomitingBySymptoms
    | DiagnosisMaternalComplications
    | DiagnosisInfection
    | DiagnosisImminentDelivery
    | DiagnosisLaborAndDelivery
    | DiagnosisHeartburn
    | DiagnosisHeartburnPersistent
    | DiagnosisDeepVeinThrombosis
    | DiagnosisPelvicPainIntense
    | DiagnosisPelvicPainContinued
    | DiagnosisUrinaryTractInfection
    | DiagnosisUrinaryTractInfectionContinued
    | DiagnosisPyelonephritis
    | DiagnosisCandidiasis
    | DiagnosisCandidiasisContinued
    | DiagnosisGonorrhea
    | DiagnosisGonorrheaContinued
    | DiagnosisTrichomonasOrBacterialVaginosis
    | DiagnosisTrichomonasOrBacterialVaginosisContinued
    | DiagnosisTuberculosis
    | DiagnosisDiabetes
    | DiagnosisGestationalDiabetes
    | DiagnosisDepressionNotLikely
    | DiagnosisDepressionPossible
    | DiagnosisDepressionHighlyPossible
    | DiagnosisDepressionProbable
    | DiagnosisSuicideRisk
    | DiagnosisOther
    | NoPrenatalDiagnosis
