<?php

/**
 * @file
 * Code for the Hedley Health Center feature.
 */

include_once 'hedley_health_center.features.inc';

/**
 * Get Clinics by health center.
 *
 * @param int $health_center_id
 *   The health center node ID.
 * @param string $type
 *   The clinic type.
 * @param int $range
 *   The queries' range.
 *
 * @return array
 *   Node IDs if they exist or empty array if no nodes exist.
 */
function hedley_health_center_get_clinics_by_health_center($health_center_id, $type, $range = 100) {
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'clinic')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_health_center', 'target_id', $health_center_id)
    ->fieldCondition('field_group_type', 'value', $type)
    ->range(0, $range);

  $result = $query->execute();

  return !empty($result['node']) ? array_keys($result['node']) : [];
}
